branches:
  only:
  - master
  - develop
  - /^greenkeeper-.*$/
  - /^greenkeeper/.*$/
language: node_js
node_js:
  - stable
  - 6
  - 5
  - 4
sudo: false
before_install: npm i -g npm@latest
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d0418713e51ac049564a
    on_success: always
    on_failure: change
    on_start: never
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
    repo_token: 9930a88506218aaf57a8349f54d5003f0bc17ce71f50df77fe0fa86884aa267b
after_script:
  - "[ $TRAVIS_NODE_VERSION = stable ] && nyc report --reporter=text-lcov | codeclimate-test-reporter"
